// claude-react-web — bin entry.
//
// Parses argv. A leading subcommand (`mcp`, `marketplace`, …) dispatches to a
// single-shot management command; otherwise it starts the Hono server on the
// chosen port and (unless --no-open) opens the user's default browser at the
// served URL.
//
// The server context (stores, SessionManager, Hono app) is built by
// server/bootstrap.ts so the desktop host shares one construction path; this
// file owns only the web-specific parts: auth gating, HTTP listen, WebSocket
// attach, browser open, and process lifecycle.

import { serve } from '@hono/node-server'
import type { Server } from 'node:http'
import { randomBytes } from 'node:crypto'
import open from 'open'
import QRCode from 'qrcode'
import pkg from '../package.json' with { type: 'json' }
import { isLoopbackHost, lanIPv4Addresses } from './net.js'
import { setWebAuth } from './auth.js'
import { loadConfig, config } from './config.js'
import { disableFileLogging, getLogFilePath, createLogger, setLogToStderr } from './log.js'
import { defaultStateDir } from './persistence.js'
import { createServerContext } from './bootstrap.js'
import { attachWebSocket } from './ws.js'
import { checkForUpdates } from './update-checker.js'
import { startEventLoopProbe } from './event-loop-probe.js'
import { normalizeClaudeConfigDirEnv } from './claude-config-dir.js'
import { parseServerArgs, parseArgv, HELP, type CliArgs } from './cli/args.js'
import { runCliCommand, topLevelHelp, GROUPS } from './cli/index.js'
import type { CliContext } from './cli/types.js'

const log = createLogger('cli')

async function main() {
  // Collapse a blank CLAUDE_CONFIG_DIR before anything resolves a CLI-owned
  // path: the SDK reads the variable directly with a nullish check, so an
  // empty value would otherwise leave its in-process helpers on a
  // cwd-relative projects/ while every server-side reader uses ~/.claude.
  normalizeClaudeConfigDirEnv()
  const argv = process.argv.slice(2)
  const { stateDir: sd, command, commandArgv } = parseArgv(argv)

  // Subcommand mode: run one management command headless and exit.
  if (command !== undefined) {
    if (!GROUPS.some((g) => g.name === command)) {
      console.error(`unknown command: ${command}`)
      process.exit(2)
    }
    const stateDir = sd ?? defaultStateDir()
    // Logger diagnostics go to stderr so stdout carries only the command's
    // result (critical for --json). Set BEFORE loadConfig so even boot logs
    // stay off the result stream.
    setLogToStderr(true)
    await loadConfig(stateDir)
    try {
      const code = await runCliCommand({ stateDir } satisfies CliContext, command, commandArgv)
      process.exit(code)
    } catch (err) {
      const e = err as { exitCode?: number; message?: string }
      console.error(e.message ?? String(err))
      process.exit(typeof e.exitCode === 'number' ? e.exitCode : 1)
    }
  }

  // Server mode (default).
  const args = parseServerArgs(argv)
  if (args.version) {
    console.log(pkg.version)
    return
  }
  if (args.help) {
    console.log(HELP)
    console.log()
    console.log(topLevelHelp())
    return
  }
  await runServer(args)
}

async function runServer(args: CliArgs): Promise<void> {
  const stateDir = args.stateDir ?? defaultStateDir()
  await loadConfig(stateDir)
  if (!config.authToken) {
    console.warn(
      '[cli] WARNING: authToken is not configured.\n' +
      '       Open the web UI to set it, or edit config.json and add:\n' +
      '         "authToken": "<your token>"',
    )
  }

  // --- Web access auth gating -----------------------------------------
  // Resolve the shared web-access token and whether auth is enforced.
  //  1) Explicit token (--token or config.accessToken) → always enforce.
  //  2) Else non-loopback host → auto-generate a token and enforce
  //     (safe-by-default when exposed to a LAN).
  //  3) Else (loopback + no token) → no auth (preserves local behavior).
  const explicitToken = args.token || config.accessToken
  const isPublic = !isLoopbackHost(args.host)
  let accessToken = explicitToken
  let authEnabled = false
  let tokenAutoGenerated = false
  if (explicitToken) {
    authEnabled = true
  } else if (isPublic) {
    accessToken = randomBytes(24).toString('base64url')
    authEnabled = true
    tokenAutoGenerated = true
  }
  setWebAuth(accessToken, authEnabled)

  const ctx = await createServerContext({
    stateDir,
    cwd: args.cwd,
    model: args.model,
    claudeBinary: args.claudeBinary,
    appPlugins: !args.disableAppPlugins,
    safeMode: args.safeMode,
    dev: args.dev,
    bind: { host: args.host, port: args.port },
  })
  const { app, sessionManager, appPluginManager } = ctx

  const { getLogConfig } = await import('./log.js')
  const initial = getLogConfig()
  log.info(
    `log: level=${initial.level}` +
      (initial.scopes ? ` scopes=${initial.scopes.join(',')}` : ' scopes=*') +
      ' (override via LOG_LEVEL / LOG_SCOPES, or PUT /api/log at runtime)',
  )
  const logFilePath = getLogFilePath()
  if (logFilePath) {
    log.info(`file logging: ${logFilePath}`)
  }

  const url = `http://${args.host}:${args.port}`
  const tokenQuery = `/?token=${accessToken}`
  const localOpenUrl = authEnabled
    ? `http://127.0.0.1:${args.port}${tokenQuery}`
    : url

  // Print the web-access summary. When auth is enabled this is the ONLY
  // place the token is logged. For LAN-reachable hosts (isPublic) each LAN
  // URL is followed by a scannable terminal QR code so a phone can open the
  // already-authenticated UI without typing the token by hand. Async because
  // QR rendering is async; a render failure degrades to the plain-text link.
  async function printAccessSummary(): Promise<void> {
    if (!authEnabled) return
    console.log('[cli] ──────────────────────────────────────────────')
    console.log('[cli] 🔒 WEB ACCESS TOKEN REQUIRED')
    if (tokenAutoGenerated) {
      console.log('[cli]    (auto-generated because the host is non-loopback)')
    }
    console.log('[cli]    Open ONE of these links to sign in:')
    console.log(`[cli]      http://127.0.0.1:${args.port}${tokenQuery}`)
    for (const ip of lanIPv4Addresses()) {
      const lanUrl = `http://${ip}:${args.port}${tokenQuery}`
      console.log(`[cli]      ${lanUrl}`)
      if (isPublic) {
        try {
          const qr = await QRCode.toString(lanUrl, { type: 'terminal', small: true })
          // QRCode emits its own multi-line block; print as-is so the
          // module quiet-zone renders correctly (no [cli] prefix).
          console.log(qr)
        } catch {
          /* QR render failed — the plain-text link above still works */
        }
      }
    }
    if (isPublic) {
      console.log('[cli]    📱 Scan a QR code above to open it on your phone.')
    }
    console.log('[cli]    WARNING: anyone on your network with this link gets')
    console.log('[cli]    FULL access (shell, files, git, API key). Keep it private.')
    if (tokenAutoGenerated) {
      console.log('[cli]    To keep a stable token across restarts, set "accessToken"')
      console.log('[cli]    in config.json or pass --token <value>.')
    }
    console.log('[cli] ──────────────────────────────────────────────')
  }

  const server = serve(
    {
      fetch: app.fetch,
      hostname: args.host,
      port: args.port,
    },
    (info) => {
      console.log(`[cli] listening on http://${info.address}:${info.port}`)
      console.log(`[cli] session idle GC active (30 min)`)

      // Fire-and-forget: prints the auth summary + QR codes. Ordered after
      // the listen log because it's awaited inside; failures are swallowed.
      void printAccessSummary()

      if (args.open) {
        open(localOpenUrl).catch(() => {
          log.info(`could not auto-open browser — visit ${localOpenUrl} manually`)
        })
      }
      // Fire-and-forget update probe. Failures are swallowed — the
      // checker writes the error to its cached snapshot, which the UI
      // can surface in the About view; we don't want to spam stdout
      // when the registry is unreachable behind a firewall. Skipped
      // entirely when no registry is configured (info.disabled).
      void checkForUpdates().then((upd) => {
        if (upd.disabled) return
        if (upd.hasUpdate && upd.latest) {
          log.info(`update available: ${upd.current} → ${upd.latest}`)
          log.info(`  run: npx claude-react-web@latest`)
        }
      }).catch(() => {})
    },
  )

  // Abrupt client deaths (process kill, network drop, proxy timeout) RST the
  // TCP socket mid-connection. Neither @hono/node-server nor — for sockets
  // erroring outside its write path — Node attach a catch-all 'error'
  // listener, and an 'error' event with NO listener crashes the whole process
  // ("Unhandled 'error' event … read ECONNRESET"; reproduced by hard-exiting
  // a single WS client). Swallow it here: every real consumer (hono, ws) has
  // its own error/close handling — this only stops the fatal unhandled-event
  // path. 'connection' fires for every TCP socket the server accepts,
  // including the ones later upgraded to WebSocket.
  server.on('connection', (socket) => {
    socket.on('error', () => {})
  })

  // Node's default `requestTimeout` (~300s) covers receiving the ENTIRE request,
  // so a large file over a slow link (phone on LAN) can be killed mid-upload.
  // Raise it well past a 500 MB upload at ~1 MB/s; a finite value keeps some
  // slowloris protection rather than disabling the timeout outright.
  ;(server as unknown as Server).requestTimeout = 30 * 60 * 1000

  // Attach the WebSocket multiplexer to the same HTTP server. The
  // returned shutdown fn closes every live socket during SIGINT.
  // @hono/node-server returns a Node http.Server (same shape), so cast
  // is safe.
  const wsShutdown = attachWebSocket(server as unknown as Server, sessionManager, ctx.appPluginEnabled ? appPluginManager : undefined)

  // Diagnostic: sample event-loop delay so a synchronous stall (which makes
  // unrelated sessions appear to hang) shows up in the logs as a max spike.
  // Default-on; disable with EVENT_LOOP_PROBE=0.
  const elProbe = startEventLoopProbe()

  const shutdown = async (signal: string) => {
    console.log(`\n[cli] received ${signal}, shutting down...`)
    elProbe.stop()
    // BEFORE any await: the same console signal that reaches us also kills
    // plugin children (no SIGINT handler) — mark their exits as expected
    // teardown, not crashes (see PluginProcessManager.shuttingDown).
    appPluginManager.prepareForShutdown()
    try {
      await wsShutdown()
    } catch (err) {
      log.error('ws shutdown error:', err)
    }
    disableFileLogging()
    // Flush every debounced store + tear down plugins/sessions. The manager
    // teardown inside ctx.shutdown stays AFTER the flushes so a plugin mid-
    // Host-call can't race the session pool teardown (Stage B2).
    try {
      await ctx.shutdown()
    } catch (err) {
      log.error('shutdown error:', err)
    } finally {
      server.close(() => process.exit(0))
      // Hard exit after 3s in case sockets are hung
      setTimeout(() => process.exit(0), 3000).unref()
    }
  }
  process.on('SIGINT', () => void shutdown('SIGINT'))
  process.on('SIGTERM', () => void shutdown('SIGTERM'))
}

main().catch((err) => {
  console.error('[cli] fatal:', err)
  process.exit(1)
})
