// AI commit-message generator for the GitPanel "This session" view.
//
// Per-call (no caching) — each diff is unique and users may regenerate
// to try different phrasings. The fallback path keeps the UI usable
// when the API is unreachable or auth is missing: we synthesise a
// `chore:` message from per-file numstat counts so the user gets
// *something* in the textarea instead of an error.

import { config as serverConfig } from './config.js'
import { callAnthropicMessages } from './anthropic-api.js'

export interface CommitMessageResult {
  /** Full commit message — first line is the subject, optional body
   *  separated by a blank line. Always non-empty. */
  message: string
  /** True when the result came from the local fallback path (auth
   *  missing, API unreachable, model returned empty). The UI shows a
   *  small badge so the user knows to massage the message themselves. */
  fallback?: boolean
}

const SYSTEM_PROMPT = `You are a commit-message assistant. Write a Conventional Commit message describing the changes shown in the unified diff.

Format:
- First line: <type>(<scope>): <subject>  — max 72 chars, lowercase, imperative mood, no trailing period
  - <type> is one of: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert
  - <scope> is optional; pick a short module or area name (e.g. "git", "ui", "api"). Omit when changes span multiple unrelated areas.
- Optional body after a blank line, wrapped to ~80 cols, explaining the *why* — not the diff content (the reader can read the diff). Keep to 1–3 short paragraphs at most.
- Do NOT include a closing signature, "Generated by", or any meta commentary.
- Output ONLY the commit message text. No code fences, no JSON, no headers.`

async function callAnthropic(diff: string, signal: AbortSignal | undefined): Promise<string> {
  const text = await callAnthropicMessages({
    model: serverConfig.commitMessageModel,
    system: SYSTEM_PROMPT,
    userContent: diff || '(empty diff)',
    // 400 covers a 72-char subject + a few-paragraph body. Larger
    // values waste cost on a model that should be terse anyway.
    maxTokens: 400,
    // Slightly higher than recap's 0.3 so the model is willing to
    // pick a definite verb / scope. Still well below "creative".
    temperature: 0.4,
    signal,
  })
  // Strip markdown code fences in case the model wraps despite the
  // instruction. Trim trailing whitespace; keep internal blank lines
  // (subject/body separator).
  return stripCodeFences(text).trimEnd()
}

/** Some models — particularly haiku variants — occasionally wrap output
 *  in ``` despite the prompt. Strip the outermost fence pair and any
 *  leading language tag. */
function stripCodeFences(s: string): string {
  const match = s.match(/^```[a-zA-Z]*\s*\n([\s\S]*?)\n```\s*$/)
  return match ? match[1] : s
}

/** Last-resort summary used when the API call fails. Reads file headers
 *  (`diff --git a/path b/path`) and per-file insertion/deletion counts
 *  from `@@` hunk markers, then concatenates a `chore: update N file(s)`
 *  with file names. Crude but never empty — and the user can edit it. */
function buildFallbackCommitMessage(diff: string): string {
  if (!diff.trim()) return 'chore: empty changeset'
  const fileLines = diff.split('\n').filter((l) => l.startsWith('diff --git '))
  const files: string[] = []
  for (const line of fileLines) {
    // Format: `diff --git a/<path> b/<path>` — pull `b/<path>`.
    const m = line.match(/^diff --git a\/.+ b\/(.+)$/)
    if (m) files.push(m[1])
  }
  if (files.length === 0) return 'chore: update files'
  const headSubject = files.length === 1
    ? `chore: update ${files[0]}`
    : `chore: update ${files.length} files`
  // Body lists at most 10 file paths to keep it bounded; remaining
  // files get a `+ N more` tail.
  const shown = files.slice(0, 10)
  const remainder = files.length - shown.length
  const body = [
    'Files changed:',
    ...shown.map((f) => `- ${f}`),
    ...(remainder > 0 ? [`- ... ${remainder} more`] : []),
  ].join('\n')
  return `${headSubject}\n\n${body}`
}

/** Generate a commit message from a unified diff. Falls back to a
 *  locally-derived `chore:` message when the API call fails for any
 *  reason (auth missing, network error, timeout, 4xx/5xx). */
export async function generateCommitMessage(
  diff: string,
  options?: { signal?: AbortSignal },
): Promise<CommitMessageResult> {
  try {
    const message = await callAnthropic(diff, options?.signal)
    if (!message.trim()) {
      // Empty model output → fall through to the fallback below rather
      // than returning an empty string the UI would reject.
      return { message: buildFallbackCommitMessage(diff), fallback: true }
    }
    return { message }
  } catch {
    return { message: buildFallbackCommitMessage(diff), fallback: true }
  }
}
