import { describe, it, expect } from 'vitest'
import { shouldHideByDefault, isLocalCommandLogUserMessage, isHumanUserMessage } from './normalize'
import type { SdkMessage } from '../types'

/** Build a top-level `user` message with the given text content (string or
 *  text-block array), mirroring how the CLI writes slash-command logs. */
function userMsg(text: string, uuid = 'u1'): SdkMessage {
  return {
    type: 'user',
    uuid,
    message: { role: 'user', content: text },
    parent_tool_use_id: null,
  } as unknown as SdkMessage
}

/** Same shape but content as a single text block (the array form the SDK
 *  uses for multimodal / structured user input). */
function userMsgBlocks(text: string, uuid = 'u1'): SdkMessage {
  return {
    type: 'user',
    uuid,
    message: { role: 'user', content: [{ type: 'text', text }] },
    parent_tool_use_id: null,
  } as unknown as SdkMessage
}

describe('isLocalCommandLogUserMessage', () => {
  it('recognizes a /model command-name invocation (string content)', () => {
    expect(
      isLocalCommandLogUserMessage(
        userMsg(
          '<command-name>/model</command-name> <command-message>model</command-message> <command-args>ppio/pa/gpt-5.5</command-args>',
        ),
      ),
    ).toBe(true)
  })

  it('recognizes a local-command-stdout line', () => {
    expect(
      isLocalCommandLogUserMessage(userMsg('<local-command-stdout>Set model to zhipuai/glm-5.2</local-command-stdout>')),
    ).toBe(true)
  })

  it('recognizes a local-command-caveat line', () => {
    expect(
      isLocalCommandLogUserMessage(userMsg('<local-command-caveat>Caveat: The messages below were generated by the user while running local commands</local-command-caveat>')),
    ).toBe(true)
  })

  it('recognizes command-log markup carried as a text block array', () => {
    expect(isLocalCommandLogUserMessage(userMsgBlocks('<command-name>/model</command-name>'))).toBe(true)
  })

  it('tolerates leading whitespace before the markup', () => {
    expect(isLocalCommandLogUserMessage(userMsg('   <command-name>/model</command-name>'))).toBe(true)
  })

  it('is case-insensitive on the tag name', () => {
    expect(isLocalCommandLogUserMessage(userMsg('<COMMAND-NAME>/model</COMMAND-NAME>'))).toBe(true)
  })

  it('does NOT match a real user message that merely mentions the tag in prose', () => {
    expect(isLocalCommandLogUserMessage(userMsg('what does <command-name> mean in the transcript?'))).toBe(false)
  })

  it('does NOT match an ordinary user prompt', () => {
    expect(isLocalCommandLogUserMessage(userMsg('review this gerrit change'))).toBe(false)
  })

  it('does NOT match a tool_result-bearing user frame (parent or not)', () => {
    const msg = {
      type: 'user',
      uuid: 'u1',
      message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: 't1', content: 'ok' }] },
      parent_tool_use_id: null,
    } as unknown as SdkMessage
    expect(isLocalCommandLogUserMessage(msg)).toBe(false)
  })

  it('does NOT match a subagent-internal user frame (parent_tool_use_id set)', () => {
    const msg = {
      type: 'user',
      uuid: 'u1',
      message: { role: 'user', content: '<command-name>/model</command-name>' },
      parent_tool_use_id: 'call_x',
    } as unknown as SdkMessage
    expect(isLocalCommandLogUserMessage(msg)).toBe(false)
  })

  it('returns false for non-user message types', () => {
    expect(isLocalCommandLogUserMessage({ type: 'assistant', uuid: 'a1' } as unknown as SdkMessage)).toBe(false)
    expect(isLocalCommandLogUserMessage({ type: 'system', subtype: 'init' } as unknown as SdkMessage)).toBe(false)
  })
})

describe('shouldHideByDefault', () => {
  it('hides a /model command-name log', () => {
    expect(shouldHideByDefault(userMsg('<command-name>/model</command-name> <command-message>model</command-message>'))).toBe(true)
  })

  it('hides a local-command-stdout log', () => {
    expect(shouldHideByDefault(userMsg('<local-command-stdout>Set model to ppio/pa/gpt-5.5</local-command-stdout>'))).toBe(true)
  })

  it('does NOT hide an ordinary user prompt', () => {
    expect(shouldHideByDefault(userMsg('review 这笔 change https://gerrit.example/c/123'))).toBe(false)
  })

  it('hides non-error/non-compact/non-retry system frames (unchanged behavior)', () => {
    expect(shouldHideByDefault({ type: 'system', subtype: 'init' } as unknown as SdkMessage)).toBe(true)
  })

  it('keeps error / compact_boundary / api_retry system frames visible (unchanged)', () => {
    expect(shouldHideByDefault({ type: 'system', subtype: 'error' } as unknown as SdkMessage)).toBe(false)
    expect(shouldHideByDefault({ type: 'system', subtype: 'compact_boundary' } as unknown as SdkMessage)).toBe(false)
    expect(shouldHideByDefault({ type: 'system', subtype: 'api_retry' } as unknown as SdkMessage)).toBe(false)
  })

  it('keeps assistant messages visible', () => {
    expect(shouldHideByDefault({ type: 'assistant', uuid: 'a1' } as unknown as SdkMessage)).toBe(false)
  })
})

describe('isHumanUserMessage', () => {
  it('does NOT classify a /model command-name log as human input', () => {
    expect(
      isHumanUserMessage(
        userMsg('<command-name>/model</command-name> <command-message>model</command-message> <command-args>ppio/pa/gpt-5.5</command-args>'),
      ),
    ).toBe(false)
  })

  it('does NOT classify a local-command-stdout log as human input', () => {
    expect(isHumanUserMessage(userMsg('<local-command-stdout>Set model to zhipuai/glm-5.2</local-command-stdout>'))).toBe(false)
  })

  it('classifies an ordinary user prompt as human input', () => {
    expect(isHumanUserMessage(userMsg('review this gerrit change'))).toBe(true)
  })

  it('does NOT classify a tool_result-bearing user frame as human input', () => {
    const msg = {
      type: 'user',
      uuid: 'u1',
      message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: 't1', content: 'ok' }] },
      parent_tool_use_id: null,
    } as unknown as SdkMessage
    expect(isHumanUserMessage(msg)).toBe(false)
  })
})
